### ISSUE TITLE
Issue #1 Code

### ISSUE THREAD

**Issue by CoolCode2** [tlaine1441/Project1#5]
I really can't speak to anything you could better -- I think everyone was impressed with your monstrous undertaking and all the logic that went into your game.  You definitely killed it, the only thing I can think of is that your .js file is so long, I could see it being broken up into multiple smaller pages.... But that is only if that is what developers do with really big files, if they don't then ignore this comment!

**Comment by tlaine1441** [comment]
Its something I really wanna do. I know there are ways but Im not sure how yet. When we learn I will be sure to do that Its so long
